apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-wjyyugak
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-wjyyugak:fe92e3b9a65bfec21f20a55b73f8485b4ef522d1@sha256:73b3aa93c5b0942b9188bef53b59b0468fba16b1431424c3c2c749a09459714b
        name: container-image  
